### ISSUE TITLE
can't run scuccess

### ISSUE THREAD

**Issue by zhangjing9898** [leftstick/vue-memory-game#4]
I have a problem
execute shell:npm start,then warn "typeError"
![image](https://user-images.githubusercontent.com/24557166/46191496-637d5100-c32a-11e8-8f18-5b772c00bf69.png)

**Comment by leftstick** [comment]
更新了一发
更新到最新代码，删除`node_modules`和`package-lock.json`，重新安装所有依赖，再运行试试
