### ISSUE TITLE
运行环境（软件及版本号）

### ISSUE THREAD

**Issue by jiaxuan-Ji** [leftstick/vue-memory-game#7]
你好，我想问下  你这个项目跑起来，需要搭建的环境有哪些？是直接在vsode运行还是说 有后端的需要用idea？可以的话详细到版本，谢谢你啦

**Comment by leftstick** [comment]
加了新章节：[Running Environment](https://github.com/leftstick/vue-memory-game#running-environment)

其实很简单，准备好开发环境，node.js，yarn。

然后下载源码，安装依赖，最后 `yarn start` 就可能 http://localhost:8080 访问了。

没有其他需求。

至于用什么ide，我源码是用vscode开发的，但这个没有强制约束，随你喜欢吧。
